version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - webnet
    depends_on:
      - db  
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=yemekdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
    volumes:
      - db_data:/var/lib/mysql
      - ./restorantt.sql:/docker-entrypoint-initdb.d/restorantt.sql
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  db_data:
    driver: local
