version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yemekdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yemekdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

volumes:
  db_data:
